name: Apibug抓取漏洞库

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:

 build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout this repo  
      uses: actions/checkout@v2

    - name: Sync Awesome-POC
      uses: actions/checkout@v2
      with: 
        repository: Threekiii/Awesome-POC
        path: Awesome-POC

    - name: Sync 2023Hvv
      uses: actions/checkout@v2
      with:
        repository: ibaiw/2023Hvv
        path: 2023Hvv

    - name: Sync Awesome-Redteam
      uses: actions/checkout@v2
      with:
        repository: Threekiii/Awesome-Redteam
        path: Awesome-Redteam

    - name: Sync yougar0.github.io
      uses: actions/checkout@v2
      with:
        repository: heise5yuetian/yougar0.github.io
        path: yougar0.github.io

    - name: Sync Vulhub-Reproduce
      uses: actions/checkout@v2
      with:
        repository: Threekiii/Vulhub-Reproduce
        path: Vulhub-Reproduce

    - name: Sync PoC-ExP
      uses: actions/checkout@v2
      with:
        repository: Cuerz/PoC-ExP
        path: PoC-ExP

    - name: Sync to my repo
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/Apibug/SecPost.git"
        source_branch: "main"
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}

node-version: 16
